---
- debug:
    msg:
      - "***********************************************************************"
      - "Running fabiohbarbosa.synapse role for {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
      - "***********************************************************************"

- name: Checking operating system distribution compatibility
  fail: msg="Role not compatibility for {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
  when: (ansible_distribution != "Ubuntu" and ansible_distribution != "Linuxmint")

- name: Set docker xenial version to apt repository
  set_fact:
     repository_version: zesty
  when: ansible_distribution_release == '{{item}}'
  with_items:
    - 'zesty'

- name: Set docker yakkety version to apt repository
  set_fact:
     repository_version: yakkety
  when: ansible_distribution_release == '{{item}}'
  with_items:
    - 'yakkety'

- name: Set docker xenial version to apt repository
  set_fact:
     repository_version: xenial
  when: ansible_distribution_release == '{{item}}'
  with_items:
    - 'xenial'
    - 'sarah'
    - 'serena'
    - 'sonya'

- name: Set docker trusty version to apt repository
  set_fact:
     repository_version: trusty
  when: ansible_distribution_release == '{{item}}'
  with_items:
    - 'trusty'
    - 'rosa'
    - 'rafaela'
    - 'rebecca'
    - 'qiana'

- name: Checking compatibility
  fail: msg="This role is not compatibility with {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
  when: repository_version is not defined

- name: Apt key for repository
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3DD99294193A09EF9270EEAFE4010F076C2225A4
  become: yes

- name: Add apt repository
  apt_repository:
    repo: deb [arch=amd64] http://ppa.launchpad.net/synapse-core/testing/ubuntu {{ repository_version }} main
    state: present
  become: yes

- name: Installing synapse
  apt:
    name:  synapse
    update_cache: yes
  become: yes